# Generated by Django 3.2 on 2021-05-30 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70, verbose_name='نام و نام خانوادگی')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='نام کاربری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='panel.category', verbose_name='دسته بندی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس تراکنش')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ به تومان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='panel.category', verbose_name='دسته بندی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
                ('people', models.ManyToManyField(to='panel.People', verbose_name='افراد')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.PositiveIntegerField(verbose_name='بدهکار')),
                ('creditor', models.PositiveIntegerField(verbose_name='بستانکار')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.people')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.transaction')),
            ],
        ),
    ]
