# Generated by Django 3.2 on 2021-11-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
