# Generated by Django 3.2 on 2021-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.AddField(
            model_name='people',
            name='fullname',
            field=models.CharField(default=1, max_length=70, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کاربری'),
        ),
    ]
