# Generated by Django 3.2 on 2021-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_people_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری'),
        ),
    ]
