# Generated by Django 3.2 on 2021-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_people_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=7, verbose_name='مبلغ به تومان'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس تراکنش'),
        ),
    ]
